# Part a)

In [2]:
import os
os.sys.path.append(os.path.dirname(os.path.abspath('.')))
from src.data.generate_data import FrankeFunction
from src.models.models import OLS
from src.features.polynomial import PolynomialFeatures
import numpy as np

In [38]:
x = np.arange(0, 1, 0.05)
y = np.arange(0, 1, 0.05)
x, y = np.meshgrid(x, y)
x, y = x.ravel(), y.ravel()
z = FrankeFunction(x, y, noise=0.01, seed=43)

In [39]:
pf = PolynomialFeatures(4)
X = pf.fit_transform(np.c_[x.reshape((-1, 1)), y.reshape((-1, 1))])
print(X)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [1.         0.05       0.         ... 0.         0.         0.        ]
 [1.         0.1        0.         ... 0.         0.         0.        ]
 ...
 [1.         0.85       0.95       ... 0.65205625 0.72876875 0.81450625]
 [1.         0.9        0.95       ... 0.731025   0.7716375  0.81450625]
 [1.         0.95       0.95       ... 0.81450625 0.81450625 0.81450625]]


In [40]:
ols = OLS()
ols.fit(X, z)

In [42]:
predictions = ols.predict(X)

# Compare some predictions to target values
print(predictions[34:40])
print(z[34:40])

[0.27985113 0.26550947 0.25611674 0.24548076 0.22586564 0.18799174]
[0.30502795 0.30526578 0.24190182 0.2435697  0.18566786 0.17013158]
